network_apis/README.md
network_apis/aggregator.py
network_apis/registry.py
network_apis/utils/logging.py
network_apis/utils/utils.py
ui/beacon_auth/wsgi.py
ui/ui/about/about.html
ui/ui/assets/main.css
ui/ui/view/view.html
ui/ui/view/view.js

Fixes #2 
Also fixes some `int` and `bool` conversions to APIs.
~~Missing feature:~~
- ~~Disable `Variant Type` if `Alternate Bases` has been filled.~~

Advanced search options

---

ui/ui/about/about.html
ui/ui/about/about.js
ui/ui/view/view.html
ui/ui/view/view.js

- Update about page to fetch Beacons from Registry instead of from Aggregator
- Add beta use notice to advanced search
- Prevent coordinate shifting when changing coord bases

UI Improvements

---

ui/ui/about/about.html
ui/ui/app.js
ui/ui/assets/main.css
ui/ui/index.html
ui/ui/newbeacon/config.json
ui/ui/newbeacon/newbeacon.html
ui/ui/newbeacon/newbeacon.js
ui/ui/view/view.html

WIP
A form to easily add new Beacons to a Registry. Fixes #13 
Also introduces a solution for Fixes #11 
To do:

Form for adding new Beacons and fixing conflicting coordinates

---

network_apis/aggregator.py
network_apis/db/docker-entrypoint-initdb.d/init.sql
network_apis/registry.py
network_apis/utils/validate.py

Fixes #15 
Continue work on #14

Require api key at POST /services

---

ui/ui/newbeacon/newbeacon.html
ui/ui/newbeacon/newbeacon.js

Adds field for API key in UI when adding new Beacons.
Relates to issues
#13 
#15 
Relates to PRs
#14 
#17

API key field in UI

---

network_apis/utils/db_ops.py
network_apis/utils/utils.py
network_apis/utils/validate.py

Went over database functions to make sure prepared statements use parameterised queries and not concatenated queries with user inputs.

Prepared and parameterised SQL

---

network_apis/aggregator.py
network_apis/registry.py
ui/ui/newbeacon/config.json
ui/ui/newbeacon/newbeacon.js

Change POST /services response from text to json in order to get ready for later changes. Adapt ui to changes.

Modify response

---

ui/ui/view/view.html

Fixes #29 
Adds a new column to display variant region in the results table.

Add region column

---

network_apis/aggregator.py
network_apis/registry.py
network_apis/schemas/serviceinfo.json
network_apis/utils/utils.py

Manage app and request security (http/https) via environment variables,.
Not writing docs to README.md, going to write proper RTD docs soon.
New functions to handle http/https thingies
```
load_certs()
application_security()
request_security()
```
New ENVs
```
APPLICATION_SECURITY  # 0-2 depending on level
REQUEST_SECURITY  # 0-2 depending on level
PATH_SSL_CERT_FILE  # path to cert.pem
PATH_SSL_KEY_FILE  # path to key.pem
PATH_SSL_CA_FILE  # path to ca.pem
```

SSL manager

---

network_apis/docs/Makefile
network_apis/docs/examples.rst
network_apis/docs/index.rst
network_apis/docs/setup.rst
network_apis/readthedocs.yml
network_apis/utils/utils.py

Documentation in RTD first stage: first few pages.

Documentation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general-issue-template.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Add:
- Contributing guidelines
- github templates
Fixes #54

Add Contributing guidelines as well as github templates

---

docs/api.rst
docs/configuration.rst
docs/examples.rst

Forward docs update from #58 to master.

Forward docs update to master

---

.coveragerc
registry/utils/utils.py
tests/aggregator/test_aggregator_endpoints.py
tests/aggregator/test_aggregator_server.py
tests/aggregator/test_aggregator_utils.py
tests/registry/test_registry_endpoints.py
tests/registry/test_registry_utils.py

More unit test coverage.
#31 (old)
* Aggregator coverage at 94%
* Registry coverage at 86%
I was unsuccessful at combining these in coveralls without majorly changing test structures, so the average 90% will not be shown. Instead the last unit tests will be shown, which happens to be the Registry at 86%.

More unit tests

---

requirements.txt

bugfix deployment build for python3.6

python3.6 dependencies

---

.github/workflows/unit-agg.yml
.github/workflows/unit-reg.yml

fix unit tests installing libcurl4-openssl-dev in github action
1. add apt-get update to unit test github actions

fix apt install

---

.github/workflows/int.yml

git lfs gets consumed fast, we need to use cache.
1. add caching to github actions

cache lfs files

---

.github/workflows/int.yml
Dockerfile
aggregator/config/__init__.py
aggregator/utils/utils.py
deploy/app.sh
registry/endpoints/services.py
registry/registry.py
registry/schemas/__init__.py
tests/aggregator/test_aggregator_utils.py
tests/integration/run_tests.py

we were importing usjon but not using it and we can use it to speed up json encoding/decoding
1. switch from json to ujson
**Might cause Rahti deployment to fail, needs testing**

switch to ujson

---

.github/workflows/int.yml

1. use beacon 2 data as url instead of lfs
2. add url as secret

use beacon 2 data as url instead of lfs

---

requirements.txt
setup.py

required for readthedocs to pass

bump jsonschema version to 4.2.1

---

.github/workflows/int.yml
setup.py
tests/integration/run_tests.py

1. package updates
2. small fix in integration tests

release 1.4.0

---

docs/examples.rst
setup.py
tests/integration/run_tests.py

- dependency updates ujson, jsonschema, tox aioresponses

1.4.1 - dependency updates

---

.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/int.yml
.github/workflows/s2i-build.yml
.github/workflows/style.yml
.github/workflows/unit.yml
docs/examples.rst
requirements.txt
setup.py
tests/integration/run_tests.py

release v1.4.2

---

.github/workflows/dependabot-auto-merge.yml

- refine conditions for auto-merge as previous ones did not work out of the box

refine condition for auto-merge

---

aggregator/aggregator.py
registry/registry.py
tests/aggregator/test_aggregator_server.py
tests/registry/test_registry_server.py

Add option to modify response headers.
Closes #178 
Added new signal to `registry` and `aggregator` apps that control response headers before response.
@blankdots hawkeye

add option to modify response headers

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/int.yml
.github/workflows/unit.yml
aggregator/utils/utils.py
docs/examples.rst
requirements.txt
setup.py
tests/integration/run_tests.py

release 1.6.5
